### ISSUE TITLE
Issue with forcedCarModel

### ISSUE THREAD

**Issue by RADMRelish86** [Stoolbend/acc-toolkit#8] opened 2023-08-17 18:23 UTC
It looks like Car Model 26 is mapped to the Ferrari 488 Challenge Evo and the BMW M4 GT3 is mapped to Car Model 30, which is backwards

**Comment by RADMRelish86** [comment] 2023-08-17 22:26
It looks like Car Model 26 is mapped to the Ferrari 488 Challenge Evo and the BMW M4 GT3 is mapped to Car Model 30, which is backwards

**Comment by Stoolbend** [comment] 2023-08-29 17:48
I'll get this sorted in the next update. I've got a 14 hour flight this week & I hope to finish a good chunk of the re-write i've been doing 👍

**Comment by RADMRelish86** [comment] 2023-10-06 02:52
It looks like there are more. The M2 shows as Porsche Cup in the toolkit

**Comment by Stoolbend** [comment] 2023-10-06 04:15
Ah bollocks. I’ll double check all the IDs tonight and update the website
tonight.
I’m just in the process of moving apartment and I’m stuck in the city hall
for the next few hours 😂

**Comment by Stoolbend** [comment] 2023-11-02 13:09
@RADMRelish86 sorry it's taken so long. I've updated the version on https://acctoolkit.bigc.industries now just in case you weren't running your own copy of it.
That has the ID numbers the correct way round for the M4 and the 488 - but I couldn't reproduce the M2 showing as a porsche cup. The ID number for the M2 is definately set to what it says on the wiki at least.
If it's still showing incorrect though then if you could possibly post a copy of an entryList JSON with the offending car in please - that'd be grand mate.

**Comment by RADMRelish86** [comment] 2023-11-02 13:17
[M2sdays Entry List.json](https://github.com/Stoolbend/acc-toolkit/files/13239171/M2sdays.Entry.List.json)

Sure mate. M2 is car model 28, and when I add the attached entry list it shows the Porsche 992 GT3 Cup Car (2022)[gtc] in the car dropdown

**Comment by Stoolbend** [comment] 2023-11-02 13:27
Ok the wiki has the wrong info then - that's what I get for not trying it first hand 😂
I'll get it fixed in a minute - just sorting the "Override driver info" buttons first.

**Comment by Stoolbend** [comment] 2023-11-02 13:39
Have swapped them around and putting your entry list on the site now shows them all as M2's 👍

**Closed by Stoolbend** 2023-11-02 13:39 UTC
Labels: bug

**Comment by RADMRelish86** [comment] 2023-11-02 13:48
Thanks!
